baseURL = 'sapii.dev'
title = "Sapii's Blog"
copyright = "Â© 2024 - Sapi or Sapii - This work is licensed under a <a href='https://creativecommons.org/licenses/by-nc-nd/4.0/' rel='license'>Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>."
canonifyurls = true
languageCode = "en-US"
paginate = 3
theme = "hugo-dusk"

googleAnalytics = ""
disqusShortname = ""

[params.author]
  name = "Sapii"
  intro = """\
   \
  """

SectionPagesMenu = "main"

[taxonomies]
  archive = "archive"
  blog = "blog"
  category = "categories"
  series = "series"
  tag = "tags"
  about = 'about'
# Configure syntax highlight
[markup]
  [markup.highlight]
    style = "gruvbox"  # dark themes: monokai, api, fruity, native, rrt, swapoff ... https://xyproto.github.io/splash/docs/longer/all.html

[[menu.main]]
  name = "About"
  weight = -130
  identifier = "about"
  url = "/about"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/blog/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"


[params.meta]
  keywords = "blog, tech, hacking, rev, web, pwn, ctf"
  description = "Sapii's Blog"

[params]
  mainSections = ['blog']
  theme_colors = "default-dark" # uses color css file under static/css/default-dark.css
  enable_separate_main_page = false # enable a separate main page with author intro and recent posts instead of the list of posts
  utterancesRepo="REPO_NAME" # Utterances is enabled when this param is set
  utterancesTheme="github-dark" # Default: github-dark
  utterancesIssueTerm="pathname" # Default: pathname

[markup.goldmark.renderer]
  unsafe = true


